services:
  - type: web
    name: facial-expression-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn facial_expression_app.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
