services:
  - type: web
    name: facial-expression-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000


